name: Lint & Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions

      - name: Install Dependencies
        run: npm install
    
      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
